services:
  - type: web
    plan: free
    name: tildeblog
    runtime: python
    buildCommand: "./render-build.sh"
    startCommand: "cd backend && python -m gunicorn mysite.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: mysite.settings.prod
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4